### ISSUE TITLE
blender addon install bug

### ISSUE THREAD

**Issue by hannesdelbeke** [plugget/plugget#13]
When trying to install `Blender-For-UnrealEngine` on plugget, we get an exception.
Unsure why this addon fails to install, other blender addons install fine.

This folder doesn't exist on my pc. so that explains the error
`C:\\Users\\user\\AppData\\Local\\Temp\\plugget\\blender\\blender-for-unrealengine`
but why does it fail for this add-on only?

log
```
open self.folder_path C:\Users\user\AppData\Local\Temp\plugget
Cloning into 'C:\Users\user\AppData\Local\Temp\plugget\plugget-pkgs'...
remote: Enumerating objects: 314, done.
remote: Counting objects: 100% (314/314), done.
remote: Compressing objects: 100% (159/159), done.
remote: Total 314 (delta 5), reused 300 (delta 4), pack-reused 0Receiving objects:  56% (176/314)
Receiving objects: 100% (314/314), 26.47 KiB | 1.89 MiB/s, done.
Resolving deltas: 100% (5/5), done.
Cloning into 'C:\Users\user\AppData\Local\Temp\plugget\plugget-pkgs2'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (6/6), done.
cloning httpsgithub.comxavier150Blender-For-UnrealEngine-Addons to C:\Users\user\AppData\Local\Temp\plugget\blender\blender-for-unrealengine\latest\blender-for-unrealengine
fatal: repository 'httpsgithub.comxavier150Blender-For-UnrealEngine-Addons' does not exist
copy files to C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons
C:\Users\user\AppData\Local\Temp\plugget\blender\blender-for-unrealengine\latest\blender-for-unrealengine\blender-for-unrealengine
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 805, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\user\\AppData\\Local\\Temp\\plugget\\blender\\blender-for-unrealengine\\latest\\blender-for-unrealengine\\blender-for-unrealengine' -> 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons\\blender-for-unrealengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\plugget_addon\__init__.py", line 235, in execute
    cmd.install(self.package_name) # todo output log
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\modules\plugget\commands\__init__.py", line 208, in install
    package.install(enable=enable, **kwargs)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\modules\plugget\data\package.py", line 290, in install
    action.install(self, *args, force=force, **kwargs)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\modules\plugget\actions\blender_addon.py", line 43, in install
    _install_addon(package)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\modules\plugget\actions\blender_addon.py", line 72, in _install_addon
    shutil.move(str(addon_path), str(local_addons_dir))
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 825, in move
    copy_function(src, real_dst)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\AppData\\Local\\Temp\\plugget\\blender\\blender-for-unrealengine\\latest\\blender-for-unrealengine\\blender-for-unrealengine'
Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 805, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\user\\AppData\\Local\\Temp\\plugget\\blender\\blender-for-unrealengine\\latest\\blender-for-unrealengine\\blender-for-unrealengine' -> 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons\\blender-for-unrealengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\plugget_addon\__init__.py", line 235, in execute
    cmd.install(self.package_name) # todo output log
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\modules\plugget\commands\__init__.py", line 208, in install
    package.install(enable=enable, **kwargs)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\modules\plugget\data\package.py", line 290, in install
    action.install(self, *args, force=force, **kwargs)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\modules\plugget\actions\blender_addon.py", line 43, in install
    _install_addon(package)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\modules\plugget\actions\blender_addon.py", line 72, in _install_addon
    shutil.move(str(addon_path), str(local_addons_dir))
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 825, in move
    copy_function(src, real_dst)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\AppData\\Local\\Temp\\plugget\\blender\\blender-for-unrealengine\\latest\\blender-for-unrealengine\\blender-for-unrealengine'
```

**Comment by hannesdelbeke** [comment]
repository `httpsgithub.comxavier150Blender-For-UnrealEngine-Addons` does not exist

**Comment by hannesdelbeke** [comment]
package was broken, fixed
