### ISSUE TITLE
issue w install tool

### ISSUE THREAD

**Issue by hannesdelbeke** [plugget/plugget#18]
installing a tool that uses qt fails when blender is already using qt.  
⚠️And plugget doesnt flag it as a failed install

repro  
- attempt to install a qt tool when blender already using qt
- get error in console window
```
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\pip\_internal\cli\base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\pip\_internal\commands\install.py", line 507, in run
    self._handle_target_dir(
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\pip\_internal\commands\install.py", line 562, in _handle_target_dir
    shutil.rmtree(target_item_dir)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 739, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 617, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\shutil.py", line 615, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\modules\\PySide2\\plugins\\imageformats\\qgif.dll'
```
- plugget install continues and think it was successfull.
but not all dependencies are installed.

workaround  
- disable qt, ensure no qt widgets are running
- install tool, which installs the dependencies. and attempts upgrade on pyside2
- the upgrade now works since qt not in use
- plugget continues install and finishes correctly

**Comment by hannesdelbeke** [comment]
still getting this for all packages with qt dependencies like bqt, pip qt addon, ...
