### ISSUE TITLE
bug if an app folder is missing in a manifest

### ISSUE THREAD

**Issue by hannesdelbeke** [plugget/plugget#22]
manifest has no maya folder `plugget-pkgs2\\maya` causing
plugget crashes

```
# Traceback (most recent call last):
#   File "C:\Users/user/Documents/maya/scripts\plugget_qt\__init__.py", line 124, in search_packages
#     packages = cmd.search(self.search_field.text())
#   File "C:\Users/user/Documents/maya/scripts\plugget\commands\__init__.py", line 159, in search
#     manifest_paths = _discover_manifest_paths(name=name, search_paths=search_paths)
#   File "C:\Users/user/Documents/maya/scripts\plugget\commands\__init__.py", line 173, in _discover_manifest_paths
#     package_dirs = [package_dir for package_dir in app_path.iterdir() if package_dir.is_dir()]
#   File "C:\Users/user/Documents/maya/scripts\plugget\commands\__init__.py", line 173, in <listcomp>
#     package_dirs = [package_dir for package_dir in app_path.iterdir() if package_dir.is_dir()]
#   File "C:\Program Files\Autodesk\Maya2024\Python\lib\pathlib.py", line 1017, in iterdir
#     for name in self._accessor.listdir(self):
# FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\user\\AppData\\Local\\Temp\\plugget\\plugget-pkgs2\\maya'
```

**Comment by hannesdelbeke** [comment]
fixed in 0.1.3
