### ISSUE TITLE
logging error in maya

### ISSUE THREAD

**Issue by hannesdelbeke** [plugget/plugget#24]
```

install requirements to target C:\Users\user\Documents\maya\2024\scripts
# Traceback (most recent call last):
#   File "C:\Users/user/Documents/maya/scripts\plugget_qt\__init__.py", line 105, in install_package
#     cmd.install(package_meta.package_name, version=version)
#   File "C:\Users/user/Documents/maya/scripts\plugget\commands\__init__.py", line 242, in install
#     package.install(enable=enable, **kwargs)
#   File "C:\Users/user/Documents/maya/scripts\plugget\data\package.py", line 345, in install
#     action.install(self, *args, force=force, **kwargs)
#   File "C:\Users/user/Documents/maya/scripts\plugget\actions\_requirements.py", line 87, in install
#     package.get_content(use_cached=True)
#   File "C:\Users/user/Documents/maya/scripts\plugget\data\package.py", line 265, in get_content
#     self._content_paths = self._clone_repo(target_dir=target_dir)
#   File "C:\Users/user/Documents/maya/scripts\plugget\data\package.py", line 282, in _clone_repo
#     logging.info("cloning", self.repo_url, "to", target_dir)
#   File "C:\Program Files\Autodesk\Maya2024\Python\lib\logging\__init__.py", line 2138, in info
#     root.info(msg, *args, **kwargs)
#   File "C:\Program Files\Autodesk\Maya2024\Python\lib\logging\__init__.py", line 1477, in info
#     self._log(INFO, msg, args, **kwargs)
#   File "C:\Program Files\Autodesk\Maya2024\Python\lib\logging\__init__.py", line 1624, in _log
#     self.handle(record)
#   File "C:\Program Files\Autodesk\Maya2024\Python\lib\logging\__init__.py", line 1634, in handle
#     self.callHandlers(record)
#   File "C:\Program Files\Autodesk\Maya2024\Python\lib\logging\__init__.py", line 1696, in callHandlers
#     hdlr.handle(record)
#   File "C:\Program Files\Autodesk\Maya2024\Python\lib\logging\__init__.py", line 968, in handle
#     self.emit(record)
#   File "C:\Program Files\Autodesk\Maya2024\Python\lib\site-packages\maya\utils.py", line 251, in emit
#     msg = self.format(record)
#   File "C:\Program Files\Autodesk\Maya2024\Python\lib\logging\__init__.py", line 943, in format
#     return fmt.format(record)
#   File "C:\Program Files\Autodesk\Maya2024\Python\lib\logging\__init__.py", line 678, in format
#     record.message = record.getMessage()
#   File "C:\Program Files\Autodesk\Maya2024\Python\lib\logging\__init__.py", line 368, in getMessage
#     msg = msg % self.args
# TypeError: not all arguments converted during string formatting
```

**Comment by hannesdelbeke** [comment]
fixed
