### ISSUE TITLE
failed re-install when pyblish alrdy installed

### ISSUE THREAD

**Issue by hannesdelbeke** [plugget/plugget#43]
```
PackagesMeta(pyblish - installed:'1.0')
PackagesMeta(reflection-locator-node - installed:'2020.03.29')
PackagesMeta(maya-pip-qt - installed:'0.0.1')
app_path C:\Users\H\AppData\Local\Temp\plugget\plugget-pkgs\maya
requirements.txt found: 'C:\Users\H\AppData\Local\Temp\plugget\maya\59e1dea8\pyblish\1.0\pyblish\requirements.txt'
requirements.txt found, uninstalling requirements
package.clone_dir / p C:\Users\H\AppData\Local\Temp\plugget\maya\59e1dea8\pyblish\1.0\pyblish\requirements.txt
# Traceback (most recent call last):
# #   File "C:\Users/H/Documents/maya/scripts\plugget_qt\__init__.py", line 62, in wrapper
    return func(self, *args, **kwargs)
# #   File "C:\Users/H/Documents/maya/scripts\plugget_qt\__init__.py", line 114, in install_package
    cmd.install(package_meta.package_name, version=version)
# #   File "C:\Users/H/Documents/maya/scripts\plugget\commands\__init__.py", line 320, in install
    package.install(enable=enable, **kwargs)
# #   File "C:\Users/H/Documents/maya/scripts\plugget\data\package.py", line 390, in install
    self.packages_meta.uninstall(self.package_name)
# #   File "C:\Users/H/Documents/maya/scripts\plugget\data\packages_meta.py", line 94, in uninstall
    p.uninstall(dependencies=dependencies, **kwargs)
# #   File "C:\Users/H/Documents/maya/scripts\plugget\data\package.py", line 442, in uninstall
    action.uninstall(self, dependencies=dependencies, *action_args, **action_kwargs)
# #   File "C:\Users/H/Documents/maya/scripts\plugget\actions\_requirements.py", line 116, in uninstall
    py_pip.uninstall(requirements=req_path, yes=True)
# #   File "C:\Users/H/Documents/maya/2024/scripts\py_pip\__init__.py", line 224, in uninstall
    unimport_modules(package_name)
# #   File "C:\Users/H/Documents/maya/2024/scripts\py_pip\__init__.py", line 198, in unimport_modules
    for module_name in get_package_modules(package_name):
# #   File "C:\Users/H/Documents/maya/2024/scripts\py_pip\__init__.py", line 183, in get_package_modules
    package_loader = pkgutil.get_loader(package_name)
# #   File "C:\Program Files\Autodesk\Maya2024\Python\lib\pkgutil.py", line 481, in get_loader
    return find_loader(fullname)
# #   File "C:\Program Files\Autodesk\Maya2024\Python\lib\pkgutil.py", line 491, in find_loader
    if fullname.startswith('.'):
# AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by hannesdelbeke** [comment]
small bug in pypip; 
but caused by plugget bug.

pypip is installed twice
once in scripts
once in scripts 2024
